import type { Locale, ExperienceSlug } from "../i18n/config";
export const privateRates = [{ key: "halfDay", price: 250 }, { key: "fullDay", price: 350 }] as const;
export const isCustomQuoteExperience = (slug: ExperienceSlug) => ["corporate-incentive-travel", "evjf-experiences", "evg-experiences"].includes(slug);
export const rateContent = {
 en: { title: "PRIVATE EXPERIENCES", halfDay: "Half day", fullDay: "Full day", unit: "per guide", travel: "Travel expenses not included.", options: "Optional services and bespoke arrangements available on request. Your quotation confirms any options and the total price before booking.", request: "Request your experience", custom: "Tailor-made quotation", reference: "Reference guide rates, when applicable", summary: "Half day €250 · Full day €350 · per guide", benefit: "Experiences led by qualified, insured local professionals." },
 fr: { title: "EXPÉRIENCES PRIVÉES", halfDay: "Demi-journée", fullDay: "Journée", unit: "par guide", travel: "Frais de déplacement non inclus.", options: "Options et organisation sur mesure sur demande. Le devis précise les options éventuelles et le prix total avant réservation.", request: "Demander votre expérience", custom: "Devis sur mesure", reference: "Tarifs de référence par guide, lorsqu’ils s’appliquent", summary: "Demi-journée 250 € · Journée 350 € · par guide", benefit: "Des expériences encadrées par des professionnels locaux qualifiés et assurés." },
 it: { title: "ESPERIENZE PRIVATE", halfDay: "Mezza giornata", fullDay: "Giornata intera", unit: "per guida", travel: "Spese di trasferta escluse.", options: "Servizi opzionali e organizzazione su misura su richiesta. Il preventivo conferma le eventuali opzioni e il prezzo totale prima della prenotazione.", request: "Richiedi la tua esperienza", custom: "Preventivo su misura", reference: "Tariffe di riferimento per guida, quando applicabili", summary: "Mezza giornata €250 · Giornata intera €350 · per guida", benefit: "Esperienze condotte da professionisti locali qualificati e assicurati." }
} satisfies Record<Locale, Record<string, string>>;
export function getGuideOffers(locale: Locale, url: string) {
 const copy = rateContent[locale];
 return privateRates.map(rate => ({ "@type": "Offer", name: `${copy[rate.key]} — ${copy.unit}`, price: rate.price, priceCurrency: "EUR", url: `${url}#private-rates`, description: `${copy.travel} ${copy.options}`, priceSpecification: { "@type": "UnitPriceSpecification", price: rate.price, priceCurrency: "EUR", referenceQuantity: { "@type": "QuantitativeValue", value: 1, unitText: copy.unit } } }));
}
