import Image from "next/image";
import Link from "next/link";
import { localePath, type Locale } from "../i18n/config";
import { getMessages } from "../i18n/messages";
import { mimosaCampaign, mimosaCopy, mimosaPhotos, mimosaArchivePhotos, mimosaPressReferences, mimosaVisualCopy, parisDate } from "../lib/mimosa-campaign";
import { getSiteUrl } from "../lib/site-url";
import { contactChannels } from "../lib/contact-channels";
import { getBusinessStructuredData, getPersonStructuredData, getBreadcrumbStructuredData, getWebPageStructuredData } from "../lib/structured-data";
import { pressStories, formatPressDate } from "../lib/press-content";
import Navbar from "./Navbar";
import Footer from "./Footer";
import MimosaBooking from "./MimosaBooking";
import styles from "./MimosaCampaign.module.css";

export default function MimosaPage({ locale }: { locale: Locale }) {
  const copy = mimosaCopy[locale]; const visual = mimosaVisualCopy[locale]; const messages = getMessages(locale);
  const gallery = [mimosaArchivePhotos[0], mimosaPhotos[1], mimosaPhotos[2], mimosaPhotos[0], mimosaArchivePhotos[1], mimosaPhotos[3]];
  const archives = ["france3-mimosa", "bbc-mimosa", "figaro-mimosa", "rcf-walking"].flatMap(id => pressStories.filter(story => story.id === id));
  const expired = parisDate() > mimosaCampaign.end;
  const url = new URL(localePath(locale, mimosaCampaign.path), getSiteUrl()).toString();
  const graph = { "@context": "https://schema.org", "@graph": [getBusinessStructuredData(locale), getPersonStructuredData(locale), getWebPageStructuredData(locale, mimosaCampaign.path, copy.name, copy.description), getBreadcrumbStructuredData(locale, [{ name: messages.navigation.home, path: "" }, { name: copy.name, path: mimosaCampaign.path }]), {
    "@type": "Service", name: copy.name, description: copy.intro, url,
    provider: { "@id": new URL("/#organization", getSiteUrl()).toString() }, areaServed: ["Cannes", "Mandelieu-la-Napoule", "Tanneron"],
    image: new URL(mimosaPhotos[0].src, getSiteUrl()).toString(),
    ...(!expired ? { offers: { "@type": "Offer", price: "250", priceCurrency: "EUR", validFrom: mimosaCampaign.start, validThrough: mimosaCampaign.end, url: `${url}#enquiry`, description: locale === "fr" ? "Prix total pour un groupe privé de 2 à 12 personnes. Goûter et guide professionnel inclus ; location de vélo non comprise. Sur demande, sans disponibilité garantie." : "Total price for a private group of 2–12. Professional guide and treat included; bicycle rental excluded. On request, with no guaranteed availability." } } : {}),
  }] };
  return <><Navbar lightBackground locale={locale} copy={messages.navigation} contactCopy={messages.contact} /><main className={styles.page}>
    <section className={styles.hero}>
      <div className={styles.heroImage}><Image src={mimosaPhotos[1].src} alt={mimosaPhotos[1].alt[locale]} fill preload sizes="(max-width:800px) 100vw, 55vw" /></div>
      <div className={`page-width ${styles.heroCopy}`}><div className={styles.heroText}>
        <p className="eyebrow">{copy.name}</p><h1>{copy.title}</h1><p className={styles.dates}>{copy.dates}</p>
        <div className={styles.heroOffer}><div className={styles.heroPrice}><strong>{locale === "fr" ? "250 €" : "€250"}</strong><span>{copy.facts[0]}</span></div><p>{visual.total}</p><span className={styles.included}>{visual.included}</span></div>
        <a href="#enquiry" className="button button-dark">{copy.discover}<span aria-hidden="true">↗</span></a>
        <p className={styles.lead}>{copy.intro}</p><ul className={styles.facts}>{copy.facts.filter((_, index) => index === 1 || index === 4).map(fact => <li key={fact}>{fact}</li>)}</ul>
      </div></div>
    </section>
    {expired && <section className={styles.section}><div className="page-width"><h2>{copy.closed}</h2><p>{copy.nextSeason}</p></div></section>}
    <section className={styles.section}><div className="page-width"><p className="eyebrow">{locale === "fr" ? "Votre groupe, votre rythme" : "Your group, your pace"}</p><h2>{copy.experiences}</h2><div className={styles.two}>
      <article className={styles.card}><div className={styles.cardImage}><Image src={mimosaPhotos[1].src} alt={mimosaPhotos[1].alt[locale]} fill sizes="(max-width:800px) 100vw, 50vw" /></div><div className={styles.cardCopy}><h3>{copy.walk}</h3><p>{copy.walkText}</p><a className="text-link" href="#enquiry">{copy.request} ↗</a></div></article>
      <article className={styles.card}><div className={styles.cardImage}><Image src="/images/experiences/mimosa-season-cycling-tour.jpg" alt={locale === "fr" ? "Illustration d’une personne à vélo sur un chemin bordé de mimosas jaunes" : "Illustration of a cyclist on a trail bordered by yellow mimosa"} fill sizes="(max-width:800px) 100vw, 50vw" /></div><div className={styles.cardCopy}><p className={styles.caption}>{locale === "fr" ? "Visuel illustratif — ne documente pas une sortie réelle" : "Illustrative image — not a record of an actual outing"}</p><h3>{copy.cycle}</h3><p>{copy.cycleText}</p><a className="text-link" href="#enquiry">{copy.request} ↗</a></div></article>
    </div><p className={styles.note}>{copy.bloom}</p></div></section>
    <section className={`${styles.section} ${styles.soft}`}><div className={`page-width ${styles.snack}`}><figure className={styles.snackScene}><div className={styles.snackFlowers}><Image src={mimosaArchivePhotos[0].src} alt={mimosaArchivePhotos[0].alt[locale]} fill sizes="(max-width:800px) 100vw, 35vw" /></div><div className={styles.snackPeople}><Image src={mimosaPhotos[1].src} alt={mimosaPhotos[1].alt[locale]} fill sizes="(max-width:800px) 45vw, 20vw" /></div><figcaption>{visual.snackCaption}</figcaption></figure><div><p className="eyebrow">{visual.snackEyebrow}</p><h2>{copy.snack}</h2><p className={styles.snackIncluded}>{visual.included}</p><p>{copy.snackText}</p><p className={styles.price}>{locale === "fr" ? "250 € pour le groupe privé" : "€250 for your private group"}</p><p>{locale === "fr" ? "Guide professionnel inclus · 2 à 12 personnes" : "Professional guide included · 2–12 people"}</p></div></div></section>
    <section className={styles.section}><div className="page-width"><h2>{copy.destinations}</h2><div className={styles.three}>{copy.places.map(place => <article className={styles.card} key={place.title}><div className={styles.cardImage}><Image src={place.src} alt="" fill sizes="(max-width:800px) 100vw, 33vw" /></div><div className={styles.cardCopy}><h3>{place.title}</h3><p>{place.text}</p><Link className="text-link" href={localePath(locale, place.href)}>{locale === "fr" ? "Explorer le secteur" : "Explore the area"} ↗</Link></div></article>)}</div></div></section>
    <section className={`${styles.section} ${styles.soft}`}><div className="page-width"><h2>{copy.gallery}</h2><p className={styles.lead}>{copy.galleryText}</p><div className={styles.gallery}>{gallery.map((photo, index) => <figure key={photo.src} className={styles[`moment${index}`]}><div className={styles.galleryPhoto}><Image src={photo.src} alt={photo.alt[locale]} fill sizes={index === 0 || index === 2 || index === 5 ? "(max-width:600px) 100vw, (max-width:1000px) 50vw, 40vw" : "(max-width:600px) 100vw, 65vw"} /></div><figcaption><span aria-hidden="true">0{index + 1}</span>{visual.galleryCaptions[index]}</figcaption></figure>)}</div></div></section>
    <section className={styles.section}><div className={`page-width ${styles.history}`}><Image src="/images/about/maddy-polomeni-mimosa-portrait.jpg" width={1280} height={720} alt={locale === "fr" ? "Maddy Polomeni auprès de mimosas en fleurs" : "Maddy Polomeni beside flowering mimosa"} sizes="(max-width:800px) 100vw, 40vw" /><div><p className="eyebrow">{visual.expertise}</p><h2>{copy.history}</h2><p className={styles.routeReference}>{visual.route}</p><p>{copy.historyText}</p><Link className="text-link" href={localePath(locale, "/press")}>{copy.press} ↗</Link>{mimosaPressReferences.length > 0 && <ul>{mimosaPressReferences.map(reference => <li key={reference.url}><a href={reference.url} target="_blank" rel="noopener noreferrer">{reference.title[locale]}{reference.date ? ` · ${reference.date}` : ""} ↗</a></li>)}</ul>}<p>{copy.professionalText}</p><div className={styles.actions}><Link className="text-link" href={localePath(locale, "/travel-trade")}>{copy.trade} ↗</Link><a className="text-link" href={`mailto:${contactChannels.primaryEmail}?subject=${encodeURIComponent(locale === "fr" ? "Presse et partenariats — Mimosa 2027" : "Press and partnerships — Mimosa 2027")}`}>{copy.pressContact} ↗</a></div></div></div></section>
    <section className={`${styles.section} ${styles.archives}`} aria-labelledby="mimosa-archives-title"><div className="page-width"><h2 id="mimosa-archives-title">{visual.archiveTitle}</h2><p>{visual.archiveNote}</p><div className={styles.pressGrid}>{archives.map(story => <article key={story.id}><p className="eyebrow">{story.publication}</p><p className={styles.archiveType}>{story.reproduction ? visual.reproduction : story.id === "rcf-walking" ? visual.interview : story.kind === "mention" ? visual.mention : visual.feature}</p><h3><a href={story.href} target="_blank" rel="noopener noreferrer">{story.titles?.[locale] ?? story.title} <span aria-hidden="true">↗</span></a></h3>{story.date && <p className={styles.archiveDate}>{formatPressDate(story.date, locale, story.datePrecision)}</p>}<p>{story.excerpts[locale]}</p></article>)}</div><div className={styles.actions}><Link className="text-link" href={localePath(locale, "/press")}>{copy.press} ↗</Link><a className="button button-dark" href={`mailto:${contactChannels.primaryEmail}?subject=${encodeURIComponent(locale === "fr" ? "Presse et partenariats — Mimosa 2027" : "Press and partnerships — Mimosa 2027")}`}>{copy.pressContact} ↗</a></div></div></section>
    <section id="enquiry" className={`${styles.section} ${styles.soft}`}><div className="page-width"><p className="eyebrow">{expired ? copy.closed : copy.dates}</p><h2>{copy.booking}</h2><div className={styles.bookingSummary}><div><p className={styles.price}>{copy.facts[2]}</p><p>{visual.total}</p><p className={styles.snackIncluded}>{visual.included}</p></div><div><h3>{visual.offerTitle}</h3><p>{visual.offerIntro}</p><ul><li>{visual.offerGuide}</li><li>{copy.facts[0]}</li><li>{visual.offerRental}</li></ul></div></div><p>{copy.schedule}</p><a className="text-link" href={mimosaCampaign.calendarSource} target="_blank" rel="noopener noreferrer">{copy.calendar} ↗</a><div className={styles.actions}><MimosaBooking locale={locale} expired={expired} /><a className="text-link" href={`tel:${contactChannels.phoneInternational}`}>{contactChannels.phoneDisplay}</a></div><div className={styles.actions}><Link href={localePath(locale, "/experiences/hiking-experiences")}>{messages.experiencePage.pages["hiking-experiences"].title} ↗</Link><Link href={localePath(locale, "/experiences/cycling-experiences")}>{messages.experiencePage.pages["cycling-experiences"].title} ↗</Link></div></div></section>
  </main><Footer locale={locale} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(graph).replace(/</g, "\\u003c") }} /></>;
}
